In [ ]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [86]:
a_1 = np.arange(11)
print(a_1)

[ 0  1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [87]:
a_2 = np.zeros((3, 3), dtype=int)
print(a_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [88]:
a_3 = np.random.randint(1, 11, (5, 5))
print(a_3)

[[ 6 10  4  2  3]
 [ 8  2  5  3  1]
 [ 7  6  2 10  2]
 [ 7  5  7  9  4]
 [ 4 10  5 10 10]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значенн

In [ ]:
a_4 = np.random.random((4, 4))
print(a_4)

[[0.85133142 0.54461808 0.56826489 0.5643494 ]
 [0.30389469 0.3353796  0.93740877 0.1946981 ]
 [0.48861283 0.46092635 0.57906778 0.69147694]
 [0.01075306 0.09179727 0.60691044 0.6444756 ]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [89]:
a_51 = np.random.randint(1, 11, 5)
print(f'1-ий масив = {a_51}')
a_52 = np.random.randint(1, 11, 5)
print(f'2-ий масив = {a_52}')
print(f'додавання = {a_51 + a_52}')
print(f'віднімання = {a_51 - a_52}')
print(f'множення = {a_51 * a_52}')

1-ий масив = [8 5 4 9 7]
2-ий масив = [2 5 6 2 1]
додавання = [10 10 10 11  8]
віднімання = [ 6  0 -2  7  6]
множення = [16 25 24 18  7]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [90]:
a_61 = np.random.randint(1, 11, 7)
print(f'1-ий вектор = {a_61}')
a_62 = np.random.randint(1, 11, 7)
print(f'2-ий вектор = {a_62}')
print(f'скалярний добуток = {np.dot(a_61, a_62)}')

1-ий вектор = [ 1  2  7 10  2 10  4]
2-ий вектор = [4 8 3 1 9 7 2]
скалярний добуток = 147


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [91]:
a_71 = np.random.randint(1, 11, (2, 2))
print(f'1-а матриця:\n{a_71}')
a_72 = np.random.randint(1, 11, (2, 3))
print(f'2-а матриця:\n{a_72}')
print(f'Множення матриць:\n{np.dot(a_71, a_72)}')

1-а матриця:
[[ 7 10]
 [ 4  7]]
2-а матриця:
[[5 3 4]
 [2 3 3]]
Множення матриць:
[[55 51 58]
 [34 33 37]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
a_8 = np.random.randint(1, 11, (3, 3))
print(f'Матриця:\n{a_8}')
a_8inv = np.linalg.inv(a_8)
print(f'Обернена матриця:\n{a_8inv}')

Матриця:
[[ 5 10 10]
 [ 5  2  6]
 [ 2  6  1]]
Обернена матриця:
[[-0.2125   0.3125   0.25   ]
 [ 0.04375 -0.09375  0.125  ]
 [ 0.1625  -0.0625  -0.25   ]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [92]:
a_9 = np.random.random((4, 4))
print(f'Матриця:\n{a_9}')
a_9t = a_9.T
print(f'Обернена матриця:\n{a_9t}')

Матриця:
[[0.66984067 0.27334297 0.2822538  0.01236854]
 [0.2720013  0.09233419 0.48248861 0.68621549]
 [0.35532774 0.02439205 0.20749433 0.66745589]
 [0.30992078 0.47103207 0.21519606 0.9314266 ]]
Обернена матриця:
[[0.66984067 0.2720013  0.35532774 0.30992078]
 [0.27334297 0.09233419 0.02439205 0.47103207]
 [0.2822538  0.48248861 0.20749433 0.21519606]
 [0.01236854 0.68621549 0.66745589 0.9314266 ]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [93]:
a_101 = np.random.randint(1, 11, (3, 4))
print(f'Матриця:\n{a_101}')
a_102 = np.random.randint(1, 11, 4)
print(f'Вектор:\n{a_102}')
product_10 = np.dot(a_101, a_102)
print(f'Множення:\n{product_10}')

Матриця:
[[ 9  9  9  2]
 [ 5 10  1  4]
 [ 6  4  9 10]]
Вектор:
[5 1 4 4]
Множення:
[ 98  55 110]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [94]:
a_111 = np.random.random((2, 3))
print(f'Матриця:\n{a_111}')
a_112 = np.random.random(3)
print(f'Вектор:\n{a_112}')
product_11 = np.dot(a_111, a_112)
print(f'Множення:\n{product_11}')

Матриця:
[[0.11950048 0.80430897 0.99522571]
 [0.83896496 0.89293867 0.5293739 ]]
Вектор:
[0.75844748 0.57892871 0.17445762]
Множення:
[0.72989709 1.245612  ]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [95]:
a_121 = np.random.randint(1, 11, (2, 2))
print(f'1-а матриця:\n{a_121}')
a_122 = np.random.randint(1, 11, (2, 2))
print(f'2-а матриця:\n{a_122}')
product_12 = a_121 * a_122
print(f'Поелементне множення:\n{product_12}')

1-а матриця:
[[ 7 10]
 [ 4  4]]
2-а матриця:
[[9 3]
 [4 3]]
Поелементне множення:
[[63 30]
 [16 12]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [96]:
a_131 = np.random.randint(1, 11, (2, 2))
print(f'1-а матриця:\n{a_131}')
a_132 = np.random.randint(1, 11, (2, 2))
print(f'2-а матриця:\n{a_132}')
product_13 = np.dot(a_131, a_132)
print(f'Множення матриць:\n{product_13}')

1-а матриця:
[[ 7  1]
 [10  5]]
2-а матриця:
[[9 8]
 [7 3]]
Множення матриць:
[[ 70  59]
 [125  95]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [97]:
a_14 = np.random.randint(1, 101, (5, 5))
print(f'Матриця:\n{a_14}')
sum_14 = a_14.sum()
print(f'Сума елементів матриці: {sum_14}')

Матриця:
[[ 63  94   9  52   3]
 [ 67  23  47  35  45]
 [ 72  81  10   3  47]
 [ 72  31  69  39  96]
 [100  30  27  75  13]]
Сума елементів матриці: 1203


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [98]:
a_151 = np.random.randint(1, 11, (4, 4))
print(f'1-а матриця:\n{a_151}')
a_152 = np.random.randint(1, 11, (4, 4))
print(f'2-а матриця:\n{a_152}')
sub_15 = a_151 - a_152
print(f'Різниця матриць:\n{sub_15}')

1-а матриця:
[[ 5  6  8  4]
 [ 2  8  5  8]
 [10  5  6  1]
 [ 1  9  5  2]]
2-а матриця:
[[ 3  7 10  5]
 [ 2  1  1  4]
 [ 7  1  3  3]
 [ 7  6  7 10]]
Різниця матриць:
[[ 2 -1 -2 -1]
 [ 0  7  4  4]
 [ 3  4  3 -2]
 [-6  3 -2 -8]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [99]:
a_16 = np.random.random((3, 3))
print(f'Матриця:\n{a_16}')
vector_column = np.sum(a_16, axis=1, keepdims=True)
print(f'Вектор-стовпчик:\n{vector_column}')

Матриця:
[[0.56425118 0.54744967 0.10443704]
 [0.88834436 0.89896629 0.55805414]
 [0.322829   0.49906979 0.5824605 ]]
Вектор-стовпчик:
[[1.21613789]
 [2.34536478]
 [1.4043593 ]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [79]:
a_17 = np.random.randint(1, 11, (3, 4))
print(f'Матриця:\n{a_17}')
squared_a_17 = np.square(a_17)
print(f'Матриця з квадратами чисел:\n{squared_a_17}')

Матриця:
[[ 9  3 10  6]
 [ 9  5  8  9]
 [ 2  9  3  4]]
Матриця з квадратами чисел:
[[ 81   9 100  36]
 [ 81  25  64  81]
 [  4  81   9  16]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [85]:
a_18 = np.random.randint(1, 51, 4)
squared_a_18 = np.sqrt(a_18)
print(f'Вектор з квадратними коренями чисел {a_18}:\n{squared_a_18}')

Вектор з квадратними коренями чисел [ 7 27 47 39]:
[2.64575131 5.19615242 6.8556546  6.244998  ]
